version: '3.9'
services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    ports:
      - "5900:5900"
      - "4444:4444"
    privileged: true
    shm_size: 2g
  pb-liga-dataloader:
    image: pbliga_webscraper_image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - chrome
    ports:
      - 8080:8080
    volumes:
      - C:/Users/Siarhei_Dubadzelau/Documents/Projects/PB-Projects/datastorage:/application/datastorage
